version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_bken
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: react_ften
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  mongodb_data:
